### ISSUE TITLE
[Question] Is it possible to use this for notifications?

### ISSUE THREAD

**Issue by grantholle** [mpbarlow/laravel-queue-debouncer#13]
Great package! I was wondering if this is restricted to just jobs, or could queued notifications be debounced as well?

**Comment by mpbarlow** [comment]
Thanks! 

It’s definitely possible, but in its current form the package doesn’t support it—I don’t _think_ the notification stuff in Laravel makes use of `Dispatchable`, though I could be mistaken. 

As a workaround you could debounce a closure that sends the notification, though. As long as your cache key provider can identify the target of the notification and the type of the notification it should do what you need.

**Comment by grantholle** [comment]
Oh, yes, that's a good idea. Didn't think about closures! Thanks.
