### ISSUE TITLE
Job Chaining

### ISSUE THREAD

**Issue by tomvo** [mpbarlow/laravel-queue-debouncer#3]
Thanks for your package, i've been trying to implement my own solution but this is so much easier and well thought out.
Quick question: How would you go about job chaining?

```
        $job = MyJob::withChain([
             new MySecondJob('a')
        ]);
```

**Comment by mpbarlow** [comment]
Thanks for your kind words. 

Does it work if you call `debounce(Bus::chain([new MyJob(), new MySecondJob()]), 30);`? 

I haven't tried it so I'm not 100% sure, but I will take a look soon and get back to you if it's something that would be easy to implement.

**Comment by tomvo** [comment]
@mpbarlow Thanks! I will also put it on my agenda to test it out this week!

**Comment by mpbarlow** [comment]
I've just pushed version 2.1.0 with support for chains. Please note that for this to work you will need to switch to the new `SerializingCacheKeyProvider`, as the default provider will debounce all chains within your app as if they were the same job. Check out the updated docs for info on how to do this.

Sorry it took so long!

**Comment by tomvo** [comment]
@mpbarlow Thanks man! We've rewritten our code to just call the jobs sequentially so we're not desperately in need anymore of this feature but i'll give it a spin as soon as we get to it. 

One other thought I had, what is your thought on leading or trailing debounce options? Like lodash's funciton, you can define if a job fires first and then debounces for X seconds or if a job is debounced for X seconds and then fired.

**Comment by mpbarlow** [comment]
@tomvo No worries! 

I did give that feature some thought, but the ways I was thinking of implementing it all required fairly large changes to how the package currently works. So I've got no current plans to add that sorry, but if you have an idea for a clean implementation, I'm open to PRs.
