### ISSUE TITLE
Feature: use arguments to uniquely debounce jobs

### ISSUE THREAD

**Issue by chrispappas** [mpbarlow/laravel-queue-debouncer#4]
A possible solution to this problem was described in #2 but that's only relevant for an older version of this package.

I think having the ability to debounce the same job, but with different arguments would be very useful and is the feature I'm looking for.

In my use case, we dispatch the same job, to update elasticsearch documents corresponding to the set of IDs passed as the job arguments. Eg. the argument might be [123, 456] or [345], or [456]. We also might end up queueing jobs with the same parameters repeatedly, and might end up with 5 instances of [456].

I want to be able to debounce the job based on the complete set of supplied parameters. So multiple [456] should be debounced into only one run after the delay expires. Same with multiple [123, 456] jobs.

I do not need the ability to debounce _within_ the arguments, just to treat each unique combination of args as its own debounced job.

**Comment by mpbarlow** [comment]
Hm, I agree this would be useful. I am aiming to look into #3 in the next couple of days; I will look into this also to see how feasible it would be to add.

In the mean time PRs are certainly welcome if you have a solution in mind already.

**Comment by mpbarlow** [comment]
I've just tagged version 2.1.0 which adds a new `SerializingCacheKeyProvider`, which will cause the same job classes with different internal state to be considered different jobs (and therefore debounced separately).

If the built-in provider doesn't quite cover your needs, there's a new `usingCacheKeyProvider` method you can call before debouncing the job, which will allow you to specify your own logic for which jobs should be considered the same or different, using a class or closure. Check out the updated readme for info on how to use this.

**Comment by chrispappas** [comment]
Thank you! Will have a look later this week when I have time. Much appreciated and very useful.
